# Generated by Django 5.2.13 on 2026-04-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("variant", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("category", models.CharField(max_length=100)),
                ("image", models.CharField(max_length=300)),
                ("inStock", models.BooleanField(default=True)),
            ],
        ),
    ]
