# Generated by Django 5.2.13 on 2026-04-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dairy", "0003_useraccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="phone",
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
