# Generated by Django 5.2.13 on 2026-04-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dairy", "0004_useraccount_is_verified_alter_useraccount_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
