# Generated by Django 5.2.13 on 2026-04-25 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dairy", "0005_alter_useraccount_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("house_flat", models.CharField(max_length=200)),
                ("area", models.CharField(max_length=200)),
                ("landmark", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=20)),
                ("delivery_instruction", models.TextField(blank=True)),
                ("leave_at_door", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="dairy.useraccount",
                    ),
                ),
            ],
        ),
    ]
